spring:
# 데이터베이스-mysql
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5
# JPA 설정
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
# flyway 설정
  flyway:
    enabled: true
    baseline-on-migrate: true

# 로그 설정
logging.level:
  org.hibernate.SQL: debug